### ISSUE TITLE
为什么每次启动都会安装一次虚拟网卡？

### ISSUE THREAD

**Issue by hyy34** [ClashrAuto/Clashr-Auto-Desktop#10]
在网络连接里，已经有好几十个名称为 TAP-Windows Adapter V9 #数字 的虚拟网卡了。测试了之后是每次启动软件，包括开机时候的自动启动，都会安装一次虚拟网卡。这个如何解决呢？
系统为win10

**Comment by ClashrAuto** [comment]
开启代理后重置路由关掉就可以了
