### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by TThityou** [ClashrAuto/Clashr-Auto-Desktop#2]
按照readme.md操作后，之后怎么操作才能让浏览器使用这个软件的代理？？我的意思是像ShadowsocksR那样，打开代理后，在浏览器设置对应的端口就可以使用，而你得readme.md没有介绍，我不是很懂怎么继续操作，希望你能回复我，谢谢

**Comment by ClashrAuto** [comment]
不需要再设置任何东西即可以通过代理使用，软件会根据访问地址自动识别是否使用代理或者直连，想要左右流量都走代理只要点击右下角选项选中global即可

**Comment by TThityou** [comment]
好的，现在有两个问题，分别是：
1. 使用global的具体方法是怎么样的？？
2..软件启动日志显示：2020/07/0311:51:47 incorrect magic number [72 8484],0x170303 is expected； 这是什么原因？解决的方案又是什么？
最后，谢谢你的回复！
