### ISSUE TITLE
[Bug] Core program closed

### ISSUE THREAD

**Issue by floatshadow** [ClashrAuto/Clashr-Auto-Desktop#24]
# 内容 Content

使用系统 system：Arch Linux

系统架构 arch：x86

软件安装方式 install mode：install (.deb package with debtap)

软件版本号 version：1.2.46

问题简要说明 message：
Core shutdown immediately after get started
KDE 4.0

软件截图 screenshots：
![screen](https://github.com/floatshadow/GraphBeds/blob/main/Screenshot_20211011_055811.png)

**Comment by ClashrAuto** [comment]
linux 需要管理员权限启动
