### ISSUE TITLE
[Bug]软件启动黑屏

### ISSUE THREAD

**Issue by SdKay** [ClashrAuto/Clashr-Auto-Desktop#28]
# 内容 Content

使用系统 system：linux, ubuntu20.04

系统架构 arch：x86

软件安装方式 install mode：deb

软件版本号 version：1.3.17

问题简要说明 message：软件终端或会计方式启动，软件黑屏；终端启动时输出：
`app.isDefaultProtocolClient('clashrauto') -> false`

软件截图 screenshots：
![Screenshot from 2021-11-05 22-20-23](https://user-images.githubusercontent.com/18526517/140525344-8bdff1e1-f6a9-46fe-9530-d9f44c66b043.png)

**Comment by zhangbo-miuNEST** [comment]
I have the same problem in Win11.

**Comment by lonee6** [comment]
win10 21h2，启动黑框，没界面。

**Comment by nickolboy** [comment]
同楼主

**Comment by ClashrAuto** [comment]
此问题请自行参考 https://clashr-auto.gitbook.io/clashr-auto/faq
