### ISSUE TITLE
关于开启软件自动获取管理员权限

### ISSUE THREAD

**Issue by DeasonHu** [ClashrAuto/Clashr-Auto-Desktop#30]
我觉得在建立快捷方式的时候，那个快捷方式本身就是会用管理员权限去打开软件的
提出这个问题最主要的原因是，我双击我的程序，程序打开cmd获取管理员权限后会很诡异的闪退，而我打开软件时直接授权管理员就没有这个问题
正是因为这个问题，我打开程序必须要右键使用管理员身份打开，也没法让软件做到开机自启动
如果把快捷方式加上用管理员身份打开exe，就可以完美解决我这个问题，而且把这个快捷方式放到C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup目录下还可以实现开机自启动，而且不用点击两次获取管理员权限也不会看到cmd的黑框框
原先程序本身的cmd获取权限也没必要删，万一有人就是跑到文件目录下双击打开，也可以自动获取权限
大概就是这样吧

关于我cmd授权之后软件闪退的问题……说真的我已经捣鼓了好几天了也没搞好……我也不知道我该提交什么资料来解决这个问题（汗.png）

**Comment by DeasonHu** [comment]
还有的时候软件出现些奇奇怪怪的问题，比如不显示节点列表啊什么的，有时候重启软件能解决，还有时候重启电脑才能解决，建议装完软件再加一个软件需要重启才能正常运行的提示

**Comment by ClashrAuto** [comment]
是的，正如你说的，如果设置管理员身份启动，在某些系统下是无法正常启动的，所以加了这个自动获取权限功能

当然也可以不用，所有这些都看个人使用习惯
