### ISSUE TITLE
[Bug]m1mac打开主界面空白

### ISSUE THREAD

**Issue by LynahZ** [ClashrAuto/Clashr-Auto-Desktop#32]
# 内容 Content

使用系统 system：macos

系统架构 arch：arm64

软件安装方式 install mode：安装 install

软件版本号 version：1.3.53

问题简要说明 message：主界面空白

软件截图 screenshots：
<img width="900" alt="图片" src="https://user-images.githubusercontent.com/15024793/155916740-5cccb1ef-e56d-4bcf-a1e9-a5554118e985.png">

**Comment by che77a38** [comment]
+1

**Comment by zoukai3412085** [comment]
me too， 1.3.58 版本，不显示任何内容，就是一个白色的窗口，也无法导入节点信息等等
