### ISSUE TITLE
主界面打不开

### ISSUE THREAD

**Issue by baiguke2019** [ClashrAuto/Clashr-Auto-Desktop#40]
系统win10

Clashr-Auto-Desktop 最新版

**Comment by baiguke2019** [comment]
已解决

便携模式
在软件目录中添加data文件夹以启动便携模式
如果用是通过安装包安装的用户，请勿在软件目录下添加data文件夹，可能导致无法正常使用等问题

**Comment by hyy34** [comment]
那用的安装版就无解了被？
