### ISSUE TITLE
[Bug]主界面无法打开

### ISSUE THREAD

**Issue by hyy34** [ClashrAuto/Clashr-Auto-Desktop#41]
# 内容 Content

使用系统 system：(windows/macos/linux) win10 和 win11

系统架构 arch：(x86/x64/arm/arm64) x64

软件安装方式 install mode：(安装 install/便携 zip/便携(含data文件夹) zip with data) 都尝试了

软件版本号 version：2.1.6

问题简要说明 message：主界面无法打开，便携版添加data文件夹情况依旧。导致无法订阅。。。只能重新回归到[1.3.53]版本

**Comment by QAQ5555** [comment]
windows10也是一样

**Comment by hyy34** [comment]
大家解决了吗？？

**Comment by AMD-WEI** [comment]
现在有个自动更新弹出来，直接更新到2.2.5了，主界面可以弹出来了
