### ISSUE TITLE
[Bug]只显示边框 没有内容 首次运行报错

### ISSUE THREAD

**Issue by sxyo** [ClashrAuto/Clashr-Auto-Desktop#43]
使用系统 system：Ubuntu22.04

系统架构 arch：x64

软件安装方式 install mode：安装 install

软件版本号 version：v2.2.8

问题简要说明 message：只显示边框 没有内容 首次运行报错 试过root运行 没有变化

软件截图 screenshots：
![image](https://user-images.githubusercontent.com/54988564/171196720-de6aa28f-80b8-4edc-bfba-c0f71a20e569.png)
![image](https://user-images.githubusercontent.com/54988564/171196762-9e7dba51-dea9-47a4-8755-f1f226edc0c8.png)

**Comment by ClashrAuto** [comment]
linux必须以ROOT权限执行
