### ISSUE TITLE
无法通过小图标退出程序选项关闭程序

### ISSUE THREAD

**Issue by movitecc** [ClashrAuto/Clashr-Auto-Desktop#5]
Linux(deepin 15.11)无法通过小图标退出程序菜单关闭程序

ps：clashr auto会跟进最新clash内核吗，界面很赞

**Comment by movitecc** [comment]
更准确点描述，右键图标，菜单栏显示可能就一秒然后自动消失

**Comment by ClashrAuto** [comment]
1.会更新最新clash内核
2.由于更新显示代理可能会造成此问题，本人也在考虑如何更好的优化此过程
